version: '3.2'

services:

  redis:
    image: redis:alpine

  datadb:
    image: postgres:9.6.3-alpine
    environment:
      - "POSTGRES_PASSWORD=123456"
    volumes:
      - "datadb:/var/lib/postgresql/data"
    ports:
      - "15432:5432"

  elasticsearch:
    image: orihoch/datapackage-pipelines-plus-plus-elasticsearch
    ports:
      - "19200:9200"
      - "19300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: orihoch/datapackage-pipelines-plus-plus-kibana
    depends_on:
      - elasticsearch
    ports:
      - "15601:5601"

  adminer:
    image: adminer
    ports:
     - "18080:8080"

  pipelines:
    depends_on:
      - redis
      - datadb
      - elasticsearch

volumes:
  datadb:
  elasticsearch:
